# Generated by Django 3.2.3 on 2021-07-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_ticket',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='seatings',
            field=models.IntegerField(blank=True, default=48, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'cancelado'), ('1', 'A tiempo'), ('2', 'en viaje'), ('3', 'finalizado')], default='1', max_length=1),
        ),
    ]
