# Generated by Django 3.2.3 on 2021-07-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0002_auto_20210715_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seatings',
            field=models.IntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('1', 'A tiempo'), ('4', 'cancelado'), ('2', 'en viaje')], default='1', max_length=1),
        ),
    ]
