# Generated by Django 3.2.3 on 2021-07-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0004_auto_20210715_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='name_seating',
            field=models.ManyToManyField(blank=True, null=True, to='app_transportAgency.Seating'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='route_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('2', 'en viaje'), ('3', 'finalizado'), ('4', 'cancelado')], default='1', max_length=1),
        ),
    ]
