# Generated by Django 3.2.3 on 2021-07-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0007_auto_20210715_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscheduling',
            name='routes',
            field=models.ManyToManyField(to='app_transportAgency.Route'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('3', 'finalizado'), ('2', 'en viaje'), ('4', 'cancelado')], default='1', max_length=1),
        ),
    ]
