# Generated by Django 3.2.3 on 2021-07-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0010_alter_tripscheduling_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_ticket',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='route_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'cancelado'), ('1', 'A tiempo'), ('2', 'en viaje'), ('3', 'finalizado')], default='1', max_length=1),
        ),
    ]
