# Generated by Django 3.2.3 on 2021-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0011_auto_20210715_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='route_schedule',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('4', 'cancelado'), ('2', 'en viaje'), ('1', 'A tiempo')], default='1', max_length=1),
        ),
    ]
