# Generated by Django 3.2.3 on 2021-07-16 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0012_auto_20210715_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_ticket',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('4', 'cancelado'), ('1', 'A tiempo'), ('2', 'en viaje')], default='1', max_length=1),
        ),
    ]
