# Generated by Django 3.2.3 on 2021-07-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0013_auto_20210715_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='route_schedule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'en viaje'), ('3', 'finalizado'), ('1', 'A tiempo'), ('4', 'cancelado')], default='1', max_length=1),
        ),
    ]
