# Generated by Django 3.2.3 on 2021-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0014_auto_20210715_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'en viaje'), ('1', 'A tiempo'), ('4', 'cancelado'), ('3', 'finalizado')], default='1', max_length=1),
        ),
    ]
