# Generated by Django 3.2.3 on 2021-07-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0016_auto_20210715_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='route_schedule',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'cancelado'), ('1', 'A tiempo'), ('2', 'en viaje'), ('3', 'finalizado')], default='1', max_length=1),
        ),
    ]
