# Generated by Django 3.2.3 on 2021-07-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0017_auto_20210715_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_ticket',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('4', 'cancelado'), ('2', 'en viaje'), ('3', 'finalizado')], default='1', max_length=1),
        ),
    ]
