# Generated by Django 3.2.3 on 2021-07-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0020_auto_20210717_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='schedule',
        ),
        migrations.AddField(
            model_name='route',
            name='schedule',
            field=models.ManyToManyField(to='app_transportAgency.Schedule'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'en viaje'), ('3', 'finalizado'), ('4', 'cancelado'), ('1', 'A tiempo')], default='1', max_length=1),
        ),
    ]
