# Generated by Django 3.2.3 on 2021-07-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0021_auto_20210718_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripscheduling',
            name='routes',
        ),
        migrations.AddField(
            model_name='tripscheduling',
            name='routes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_transportAgency.route'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('2', 'en viaje'), ('3', 'finalizado'), ('4', 'cancelado')], default='1', max_length=1),
        ),
    ]
