# Generated by Django 3.2.3 on 2021-07-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0023_auto_20210718_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.RemoveField(
            model_name='route',
            name='schedule',
        ),
        migrations.AddField(
            model_name='route',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transportAgency.schedule'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('4', 'cancelado'), ('2', 'en viaje'), ('1', 'A tiempo')], default='1', max_length=1),
        ),
    ]
