# Generated by Django 3.2.3 on 2021-07-20 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0024_auto_20210719_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('1', 'A tiempo'), ('4', 'cancelado'), ('2', 'en viaje')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='route',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny_city', to='app_transportAgency.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_city', to='app_transportAgency.city'),
        ),
    ]
