# Generated by Django 3.2.3 on 2021-07-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0025_auto_20210719_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='route',
            name='route_time',
            field=models.IntegerField(),
        ),
    ]
