# Generated by Django 3.2.3 on 2021-07-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0026_auto_20210719_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'en viaje'), ('1', 'A tiempo'), ('4', 'cancelado'), ('3', 'finalizado')], max_length=1),
        ),
    ]
