# Generated by Django 3.2.3 on 2021-07-23 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0028_auto_20210722_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transportAgency.tripscheduling'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('2', 'en viaje'), ('3', 'finalizado'), ('4', 'cancelado')], max_length=1),
        ),
    ]
