# Generated by Django 3.2.3 on 2021-07-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0034_alter_tripscheduling_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatassignment',
            old_name='trips',
            new_name='trip',
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('3', 'finalizado'), ('2', 'en viaje'), ('4', 'cancelado')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together={('trip', 'seating')},
        ),
        migrations.RemoveField(
            model_name='seatassignment',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='seatassignment',
            name='client',
        ),
    ]
