# Generated by Django 3.2.3 on 2021-07-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0035_auto_20210723_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_reservation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'cancelado'), ('3', 'finalizado'), ('2', 'en viaje'), ('1', 'A tiempo')], max_length=1),
        ),
    ]
