# Generated by Django 3.2.3 on 2021-07-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0036_auto_20210723_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_available',
            field=models.IntegerField(blank=True, default=16, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('2', 'en viaje'), ('4', 'cancelado'), ('3', 'finalizado')], max_length=1),
        ),
    ]
