# Generated by Django 3.2.3 on 2021-07-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0037_auto_20210723_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transportAgency.client'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'en viaje'), ('3', 'finalizado'), ('1', 'A tiempo'), ('4', 'cancelado')], max_length=1),
        ),
    ]
