# Generated by Django 3.2.3 on 2021-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0038_auto_20210723_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('1', 'A tiempo'), ('4', 'cancelado'), ('2', 'en viaje')], max_length=1),
        ),
    ]
