# Generated by Django 3.2.3 on 2021-07-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0039_alter_tripscheduling_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'cancelado'), ('2', 'en viaje'), ('3', 'finalizado'), ('1', 'A tiempo')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together={('trip', 'seating', 'client')},
        ),
    ]
