# Generated by Django 3.2.3 on 2021-07-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0040_auto_20210723_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatassignment',
            name='seating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transportAgency.seating'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('4', 'cancelado'), ('3', 'finalizado'), ('2', 'en viaje')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together={('trip', 'seating')},
        ),
    ]
