# Generated by Django 3.2.3 on 2021-07-23 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0041_auto_20210723_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatassignment',
            name='seating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transportAgency.seating'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'en viaje'), ('1', 'A tiempo'), ('4', 'cancelado'), ('3', 'finalizado')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together={('seating', 'client')},
        ),
    ]
