# Generated by Django 3.2.3 on 2021-07-23 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0042_auto_20210723_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='ticket_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transportAgency.ticket'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('1', 'A tiempo'), ('4', 'cancelado'), ('2', 'en viaje')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='seatassignment',
            name='trip',
        ),
    ]
