# Generated by Django 3.2.3 on 2021-07-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0043_auto_20210723_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_reservation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'cancelado'), ('1', 'A tiempo'), ('2', 'en viaje'), ('3', 'finalizado')], max_length=1),
        ),
    ]
