# Generated by Django 3.2.3 on 2021-07-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0044_auto_20210723_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_reservation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('4', 'cancelado'), ('3', 'finalizado'), ('2', 'en viaje')], max_length=1),
        ),
    ]
