# Generated by Django 3.2.3 on 2021-07-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0046_auto_20210723_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatassignment',
            name='bus',
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'en viaje'), ('3', 'finalizado'), ('4', 'cancelado'), ('1', 'A tiempo')], max_length=1),
        ),
    ]
