# Generated by Django 3.2.3 on 2021-07-24 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0047_auto_20210723_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='routes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transportAgency.route'),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='ticket_reservation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('2', 'en viaje'), ('1', 'A tiempo'), ('4', 'cancelado')], max_length=1),
        ),
    ]
