# Generated by Django 3.2.3 on 2021-07-24 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0050_alter_tripscheduling_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_transportAgency.seating'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('4', 'cancelado'), ('1', 'A tiempo'), ('2', 'en viaje')], max_length=1),
        ),
    ]
