# Generated by Django 3.2.3 on 2021-07-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0051_auto_20210723_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companion_tciket', to='app_transportAgency.client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_ticket', to='app_transportAgency.client'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'finalizado'), ('2', 'en viaje'), ('4', 'cancelado'), ('1', 'A tiempo')], max_length=1),
        ),
        migrations.DeleteModel(
            name='SeatAssignment',
        ),
    ]
