# Generated by Django 3.2.3 on 2021-07-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0052_auto_20210724_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripscheduling',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'cancelado'), ('3', 'finalizado'), ('2', 'en viaje'), ('1', 'A tiempo')], max_length=1),
        ),
    ]
