# Generated by Django 3.2.3 on 2021-07-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0053_auto_20210730_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'Cancelado'), ('2', 'En viaje'), ('3', 'Finalizado'), ('1', 'A tiempo')], max_length=1),
        ),
    ]
