# Generated by Django 3.2.3 on 2021-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0054_auto_20210730_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dni',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('2', 'En viaje'), ('3', 'Finalizado'), ('4', 'Cancelado')], max_length=1),
        ),
    ]
