# Generated by Django 3.2.3 on 2021-08-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0054_alter_tripscheduling_state'),
        ('app_transportAgency', '0055_auto_20210731_0013'),
    ]

    operations = [
    ]
