# Generated by Django 3.2.3 on 2021-08-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0056_merge_20210802_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_ticket', to='app_transportAgency.client'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'Finalizado'), ('4', 'Cancelado'), ('1', 'A tiempo'), ('2', 'En viaje')], max_length=1),
        ),
    ]
