# Generated by Django 3.2.3 on 2021-08-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0057_auto_20210803_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='companion',
        ),
        migrations.AddField(
            model_name='ticket',
            name='companion',
            field=models.ManyToManyField(blank=True, null=True, related_name='companion_ticket', to='app_transportAgency.Client'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seating',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seating',
            field=models.ManyToManyField(blank=True, null=True, to='app_transportAgency.Seating'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('1', 'A tiempo'), ('4', 'Cancelado'), ('3', 'Finalizado'), ('2', 'En viaje')], max_length=1),
        ),
    ]
