# Generated by Django 3.2.3 on 2021-08-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0058_auto_20210803_0432'),
        ('app_transportAgency', '0058_auto_20210803_0956'),
    ]

    operations = [
    ]
