# Generated by Django 3.2.3 on 2021-08-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0059_merge_0058_auto_20210803_0432_0058_auto_20210803_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transportAgency.bus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_transportAgency.bus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='companion',
            field=models.ManyToManyField(related_name='companion_ticket', to='app_transportAgency.Client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seating',
            field=models.ManyToManyField(to='app_transportAgency.Seating'),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'En viaje'), ('3', 'Finalizado'), ('4', 'Cancelado'), ('1', 'A tiempo')], max_length=1),
        ),
    ]
