# Generated by Django 3.2.3 on 2021-08-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0060_auto_20210804_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('2', 'En viaje'), ('4', 'Cancelado'), ('1', 'A tiempo'), ('3', 'Finalizado')], max_length=1),
        ),
    ]
