# Generated by Django 3.2.3 on 2021-08-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0061_alter_tripscheduling_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('4', 'Cancelado'), ('1', 'A tiempo'), ('3', 'Finalizado'), ('2', 'En viaje')], max_length=1),
        ),
    ]
