# Generated by Django 3.2.3 on 2021-08-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transportAgency', '0062_auto_20210804_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='tripscheduling',
            name='state',
            field=models.CharField(choices=[('3', 'Finalizado'), ('4', 'Cancelado'), ('2', 'En viaje'), ('1', 'A tiempo')], max_length=1),
        ),
    ]
